# Turn on light when pausing Chromecast, after sundown
- alias: "MONITOR: Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'playing'
      to: 'paused'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.stue_normal_light

# Dim lights when playing Chromecast after sundown
- alias: "MONITOR: Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.stue_dimmed_tv_light
