# Show Ole Telefon location
- platform: generic
  name: Ole
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ole_s9plus.attributes.latitude }},{{ states.device_tracker.ole_s9plus.attributes.longitude }}&zoom=14&size=492x492&maptype=roadmap&markers=color:black%7Clabel:Ole%7C{{ states.device_tracker.ole_s9plus.attributes.latitude }},{{ states.device_tracker.ole_s9plus.attributes.longitude }}&key=AIzaSyAXakuuAtwXYnGmbOgeNerfMWzRa9Hfw2g
  limit_refetch_to_url_change: false

# International Space Station location
#  - platform: generic
#    name: ISS
#    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.latitude }},{{ states.binary_sensor.iss.attributes.longitude }}&zoom=5&size=500x500&maptype=roadmap&markers=color:white%7Clabel:ISS%7C{{ states.binary_sensor.iss.attributes.latitude }},{{ states.binary_sensor.iss.attributes.longitude }}
#    limit_refetch_to_url_change: true

# Show YR.no weather Svendborg
- platform: generic
  name: Weather
  still_image_url: https://www.yr.no/sted/Danmark/Syddanmark/Svendborg//meteogram.svg
  content_type: 'image/svg+xml'

- platform: mjpeg
  name: D-Link Webcam
  still_image_url: http://10.0.0.23/image/jpeg.cgi
  mjpeg_url: http://10.0.0.23/video.cgi

- platform: generic
  name: Netbox Topology
  still_image_url: 'http://doc.olenoerby.dk/api/extras/topology-maps/1/render'
  content_type: 'image/png'
  authentication: basic
  username: !secret netbox_username
  password: !secret netbox_password
