homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_above_sea_level
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

config:
discovery:
conversation:
map:
updater:

frontend:
  javascript_version: latest

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: /etc/letsencrypt/live/home.dvice.dk/fullchain.pem
  ssl_key: /etc/letsencrypt/live/home.dvice.dk/privkey.pem

# Logging to homeassistant.log
logger: !include logger.yaml


automation: !include_dir_merge_list automation
# script: !include_dir_merge_list scripts
shell_command: !include_dir_merge_list shell_commands
notify: !include notify.yaml
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors
# switch: !include switches.yaml
group: !include groups.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
influxdb: !include influxdb.yaml

# IKEA Trådfri
tradfri:
  host: !secret tradfri_ip

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 40
    waypoints: True
    waypoint_whitelist:
      - ha
      - Ole
  - platform: bluetooth_tracker
  - platform: aruba
    host: !secret aruba_virtual_controller_ip
    username: !secret aruba_ap_user
    password: !secret aruba_ap_password

input_boolean:
  ole_home:
    name: Ole Home Presence
    initial: on
    icon: mdi:account

  guests_at_home:
    name: Guests at Home
    initial: off
    icon: mdi:account-multiple

#alert:
#  uv_index:
#    name: UV Index is higher than 3
#    done_message: I'm protected
#    entity_id: binary_sensor.dark_sky_uv_index_high
#    can_acknowledge: True
#    repeat:
#      - 15
#      - 60
#      - 240
#    notifiers:
#      - notify.jeeves
    
  

# Connect to MQTT server
mqtt:
  broker: m21.cloudmqtt.com
  port: 14253
  username: ha
  password: !secret mqtt_password

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - weather
      - camera
      - flux
      - automation
      - pihole
      - httplogin
      - history_graph
      - group
      - pihole
      - script
      - view
      - automation
      - time
      - sun
    entities:
      - sensor.current_version
      - sensor.time
      - sensor.date
      - sensor.time_utc
      - camera.weather
      - boolean_input.hygge_mode
      - sensor.weather_symbol
      - sensor.ssl_cert_expiry
      - sensor.last_boot
      - sensor.disk_used_home
      - sensor.ram_available
      - sensor.ipv4_address_enxb827ebe1df58
      - binary_sensor.workday_sensor
      - input_boolean.ole_home
      - sensor.battery
      - sensor.drive_to_home
      - sensor.phone_bike_to_home

      - sensor.weather_cloudiness
      - sensor.weather_direction

      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1
      - sensor.dark_sky_icon_2
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_1
      - sensor.dark_sky_uv_index_2

      - sensor.pihole_domains_blocked
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today

      - light.entre
      - light.stue
      - light.sovevrelse
      - light.gang
      - sensor.tradfri_motion_sensor
      - sensor.remote

      - sensor.alpha_cpu_usage
      - sensor.alpha_memory_usage      
      - sensor.alpha_volume_used_datavol1_2
      - sensor.terra_cpu_usage
      - sensor.terra_memory_usage

      - sensor.lastfm_leutnant13_playcount

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.time_utc

# Track the sun
sun:

# Binary sensors
binary_sensor: !include_dir_merge_list binary_sensors


# Generate graphs
history_graph:
  graph_pihole:
    name: Pihole Blocked Ads Today
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
    hours_to_show: 48
    refresh: 60

  graph_speedtest_down:
    name: Speedtest Download Results
    entities:
    - sensor.speedtest_download
    hours_to_show: 48
    refresh: 900

  graph_speedtest_up:
    name: Speedtest Upload Results
    entities:
    - sensor.speedtest_upload
    hours_to_show: 48
    refresh: 900

  graph_mails:
    name: Unread
    entities:
    - sensor.oledvicedk
    hours_to_show: 48
    refresh: 60


switch:
#Flux light control
#   - platform: flux
#     lights:
#       - light.gang_loftlampe
#       - light.sovevrelse_stander_hvidt_spektrum
#       - light.entre_loftlampe
#     start_time: '7:00'
#     stop_time: '22:00'
#     start_colortemp: 1250
#     stop_colortemp: 1457
#     brightness: 2
#     mode: mired

cast:

# Text to speech
#tts:
#   platform: google

weather:
  - platform: yweather

camera:
# Show Ole Telefon location
  - platform: generic
    name: Ole
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ole_telefon.attributes.latitude }},{{ states.device_tracker.ole_telefon.attributes.longitude }}&zoom=14&size=492x492&maptype=roadmap&markers=color:black%7Clabel:Ole%7C{{ states.device_tracker.ole_telefon.attributes.latitude }},{{ states.device_tracker.ole_telefon.attributes.longitude }}
    limit_refetch_to_url_change: true

# International Space Station location
#  - platform: generic
#    name: ISS
#    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.latitude }},{{ states.binary_sensor.iss.attributes.longitude }}&zoom=5&size=500x500&maptype=roadmap&markers=color:white%7Clabel:ISS%7C{{ states.binary_sensor.iss.attributes.latitude }},{{ states.binary_sensor.iss.attributes.longitude }}
#    limit_refetch_to_url_change: true

# Show YR.no weather Svendborg
  - platform: generic
    name: Weather
    still_image_url: https://www.yr.no/sted/Danmark/Syddanmark/Svendborg//meteogram.svg
    content_type: 'image/svg+xml'

  - platform: mjpeg
    name: D-Link Webcam
    still_image_url: http://10.0.0.23/image/jpeg.cgi
    mjpeg_url: http://10.0.0.23/video.cgi


  
  





