homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_above_sea_level
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

config:
discovery:
conversation:
map:
updater:
sun:
#cast:
camera: !include camera.yaml
#influxdb: !include influxdb.yaml
group: !include groups.yaml
logger: !include logger.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
zone: !include zones.yaml

# FOLDERS
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
# switch: !include switches.yaml



###### CONFIGURATION BEGINNING ######

frontend:
  javascript_version: latest

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path


# IKEA Trådfri
tradfri:
  host: !secret tradfri_ip

device_tracker:
  - platform: traccar
    username: !secret traccar_user
    password: !secret traccar_password
    host: !secret traccar_host

  - platform: bluetooth_tracker
    track_new_devices: false

  - platform: aruba
    host: !secret aruba_virtual_controller_ip
    username: !secret aruba_ap_user
    password: !secret aruba_ap_password
    track_new_devices: false

input_boolean:
  ole_home:
    name: Ole Home Presence
    initial: on
    icon: mdi:account

  guests_at_home:
    name: Guests at Home
    initial: off
    icon: mdi:account-multiple

#alert:
#  uv_index:
#    name: UV Index is higher than 3
#    done_message: I'm protected
#    entity_id: binary_sensor.dark_sky_uv_index_high
#    can_acknowledge: True
#    repeat:
#      - 15
#      - 60
#      - 240
#    notifiers:
#      - notify.jeeves
    
  

# Connect to MQTT server
mqtt:
  broker: !secret mqtt_broker
  port: 14253
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - weather
      - camera
      - flux
      - automation
      - pihole
      - httplogin
      - history_graph
      - group
      - pihole
      - script
      - view
      - automation
      - time
      - sun
    entities:
      - sensor.current_version
      - sensor.time
      - sensor.date
      - sensor.time_utc

      - boolean_input.hygge_mode
      - sensor.weather_symbol
      - sensor.ssl_cert_expiry
      - sensor.last_boot
      - sensor.disk_used_home
      - sensor.ram_available
      - sensor.ipv4_address_enxb827ebe1df58
      - binary_sensor.workday_sensor
      - input_boolean.ole_home
      - sensor.battery
      - sensor.drive_to_home
      - sensor.phone_bike_to_home

      - sensor.weather_cloudiness
      - sensor.weather_direction

      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1
      - sensor.dark_sky_icon_2
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_1
      - sensor.dark_sky_uv_index_2

      - sensor.pihole_domains_blocked
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today

      - light.entre
      - light.stue
      - light.sovevrelse
      - light.gang
      - sensor.tradfri_motion_sensor
      - sensor.remote

      - sensor.alpha_cpu_usage
      - sensor.alpha_memory_usage      
      - sensor.alpha_volume_used_datavol1_2
      - sensor.terra_cpu_usage
      - sensor.terra_memory_usage

      - sensor.lastfm_leutnant13_playcount

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.time_utc

#panel_iframe:
#  nodered:
#    title: Node-RED
#    url: http://home.dvice.dk:1880 
#    icon: mdi:nodejs

# Generate graphs
history_graph:
  graph_pihole:
    name: Pihole Blocked Ads Today
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
    hours_to_show: 48
    refresh: 60

  graph_speedtest_down:
    name: Speedtest Download Results
    entities:
    - sensor.speedtest_download
    hours_to_show: 48
    refresh: 900

  graph_speedtest_up:
    name: Speedtest Upload Results
    entities:
    - sensor.speedtest_upload
    hours_to_show: 48
    refresh: 900

  graph_mails:
    name: Unread
    entities:
    - sensor.olemail
    hours_to_show: 48
    refresh: 60



# Text to speech
#tts:
#   platform: google

# Google Assistant
google_assistant:
  project_id: !secret project_id
  client_id: !secret client_id
  agent_user_id: !secret agent_user_id
  api_key: !secret api_key
  access_token: !secret access_token
  exposed_domains:
    - light

weather:
  - platform: yweather
