- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'

- platform: darksky
  api_key: !secret dark_sky_api_key
  latitude: 55.0639709
  longitude: 10.6370836
  units: si
  forecast:
    - 1
    - 2
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - uv_index

# Versionchecker
- platform: version

# SSL certificate check
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/home.dvice.dk/cert.pem | awk '{ print $NF }'"

- platform: qnap
  host: 10.0.0.8
  port: 443
  ssl: true
  verify_ssl: false
  username: admin
  password: !secret qnap_pw
  monitored_conditions:
    - status
    - cpu_usage
    - network_rx
    - network_tx
    - memory_percent_used
    - volume_percentage_used
    - volume_size_free

- platform: qnap
  host: 10.0.0.9
  port: 443
  ssl: true
  verify_ssl: false
  username: admin
  password: !secret qnap_pw
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - volume_percentage_used
    - volume_size_free


# Day or Night sensor
- platform: template
  sensors:
    day_night:
      friendly_name: "Day/Night"
      value_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          Day
        {% else %}
          Night
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}

# Weather Prediction
- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - cloudiness

# Speedtest sensor
- platform: speedtest
  minute:
    - 0
    - 20
    - 40
  monitored_conditions:
    - ping
    - download
    - upload

# Pihole sensor
- platform: pi_hole
  host: 10.0.0.10
  location: admin
  ssl: false
  monitored_conditions:
  - ads_blocked_today
  - ads_percentage_today
  - dns_queries_today
  - domains_being_blocked
  - queries_forwarded
  - queries_cached
  - unique_clients
  - unique_domains

# Google Maps time travel home sensor
- platform: google_travel_time
  name: Drive to Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.ole_telefon
  destination: zone.home
# Google Maps time BIKE travel home sensor
- platform: google_travel_time
  name: Phone Bike to Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.ole_telefon
  destination: zone.home
  options:
    mode: bicycling
- platform: google_travel_time
  name: Drive to work
  api_key: !secret google_maps_api_key
  origin: device_tracker.ole_telefon
  destination: Englandsvej 8, 5700 Svendborg

- platform: mqtt
  state_topic: "owntracks/Ole/Telefon"
  name: "SGS7 Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: imap
  server: mail.dvice.dk
  port: 993
  username: !secret ole_mail_address
  password: !secret ole_mail_pw

# System Monitor sensor
- platform: systemmonitor
  resources:
    - type: ipv4_address
      arg: enxb827ebe1df58
    - type: last_boot


# Steam Sensor
- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - 76561198003340322
    - 76561198049340420
    - 76561198003063216

# Twitch streamers online  
- platform: twitch
  channels:
    - nerdcubed

#Last.FM
- platform: lastfm
  api_key: !secret lastfm_api_key
  users:
    - leutnant13

- platform: template
  sensors:
   lastfm_leutnant13_playcount:
     unit_of_measurement: 'plays'
     value_template: "{{ states.sensor.lastfm_leutnant13.attributes.play_count }}"

- platform: template
  sensors:
    sun_elevation:
      unit_of_measurement: '°'
      value_template: "{{ states.sun.sun.attributes.elevation }}"
