title: Lovelace UI

views:
  - title: Frontpage
    id: home
    theme: light-mode
    cards:
      - type: glance
        title: Quick-view
        entities:
          - sensor.time
          - sensor.date
          - entity: sensor.weather_symbol
            name: Weather
          - entity: sensor.dark_sky_uv_index
            name: UV level
      
      - type: entity-filter
        entities:
          - entity: device_tracker.ole_telefon
            name: Ole
        state_filter:
          - "Work"
          - "Home"
          - "School"

      - type: picture-entity
        title: Aquarium
        entity: camera.dlink_webcam
        show_info: false

      - type: picture
        title: Weather
        image: "https://www.yr.no/sted/Danmark/Syddanmark/Svendborg/meteogram.svg"
        navigation_path: /lovelace/weather

      - type: media-control
        entity: media_player.living_room_tv

      - type: vertical-stack
        name: Media Players
        cards:
          - type: entities
            entities: 
              - media_player.living_room_tv
              - media_player.living_room_speaker_2

      - type: map
        name: Tracked Devices
        entities:
          - entity: device_tracker.ole_telefon
          - zone.home

      - type: vertical-stack
        name: Phone Tracking
        cards: 
          - type: entities
            entities:
              - sensor.drive_to_home
              - sensor.phone_bike_to_home
              - sensor.drive_to_work
          - type: entities
            entities:
              - sensor.sgs7_battery

  - title: Lights
    id: lights
    theme: light-mode
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.stue_stander_hvidt_spektrum
                name: Stue Standerlampe
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.stue_spot_hjre_varm_hvid_3
                  - entity: light.stue_spot_midt_varm_hvid_2
                  - entity: light.stue_spot_venstre_varm_hvid_1
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.entre_loftlampe
                name: Entré
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.sovevrelse_stander_hvidt_spektrum
                name: Soveværelse
              - entity: light.gang_loftlampe
                name: Gang

      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.toilet
                name: Badeværelse


  - title: Weather
    id: weather
    theme: light-mode
    cards:
      - type: "custom:weather-card"
        entity_weather: weather.yweather
        entity_sun: sun.sun
      - type: "custom:weather-card"
        entity_weather: weather.yweather
        entity_sun: sun.sun
      - type: entities
        title: Weather
        entities:
          - sensor.pws_weather
          - sensor.pws_temp_f
          - sensor.pws_relative_humidity
          - sensor.pws_wind_string
          - sensor.dark_sky_cloud_coverage
          - sensor.pollen_level
          - sensor.cold_flu_risk
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary


  - title: Social
    id: social
    theme: light-mode
    cards:


  - title: Networking
    id: networking
    theme: light-mode
    cards:

  - title: Information
    id: info
    theme: light-mode
    cards:

  - title: Automations
    id: automation
    theme: light-mode
    cards: