title: Lovelace UI

views:
  - title: Frontpage
    id: home
    theme: light-mode
    cards:
      - type: glance
        title: Quick-view
        entities:
          - sensor.time
          - sensor.date
          - entity: sensor.weather_symbol
            name: Weather
          - entity: sensor.dark_sky_uv_index
            name: UV level
      
      - type: entities
        entities:
          - entity: device_tracker.ole_s9plus
            name: Ole
        state_filter:
          - Work
          - Home
          - School
        show_empty: false

      - type: picture-entity
        title: Aquarium
        entity: camera.dlink_webcam
        show_info: false

      - type: picture
        title: Weather
        image: "https://www.yr.no/sted/Danmark/Syddanmark/Svendborg/meteogram.svg"
        navigation_path: /lovelace/weather

      - type: media-control
        entity: media_player.living_room_tv

      - type: media-control
        entity: media_player.living_room_speaker

      - type: vertical-stack
        name: Media Players
        cards:
          - type: entities
            entities: 
              - media_player.living_room_tv
              - media_player.living_room_speaker

      - type: map
        name: Tracked Devices
        entities:
          - entity: device_tracker.ole_s9plus
          - zone.home

      - type: vertical-stack
        name: Phone Tracking
        cards: 
          - type: entities
            entities:
              - sensor.drive_to_home
              - sensor.phone_bike_to_home
              - sensor.drive_to_work
          - type: entities
            entities:
              - sensor.phone_battery

  - title: Lights
    id: lights
    theme: light-mode
    cards:
      - type: vertical-stack
        title: Stue
        cards:
          - type: entities
            entities:
              - entity: light.stue_stander_hvidt_spektrum
                name: Stue Standerlampe
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: light.stue_spot_hjre_varm_hvid_3
                  - entity: light.stue_spot_midt_varm_hvid_2
                  - entity: light.stue_spot_venstre_varm_hvid_1
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.entre_loftlampe
                name: Entré
      
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.sovevrelse_stander_hvidt_spektrum
                name: Soveværelse
              - entity: light.gang_loftlampe
                name: Gang

      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.toilet
                name: Badeværelse


  - title: Weather
    id: weather
    theme: light-mode
    cards:
      - type: "weather-forecast"
        title: "Weather Forecast"
        entity: weather.yweather

      - type: entities
        title: Weather Summary
        entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary

      - type: entities
        title: UV Index
        entities:
          - sensor.dark_sky_uv_index

      - type: entities
        title: Temperatures
        entities:
          - sensor.dark_sky_temperature
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_humidity


      - type: entities
        title: Rain Precipitation
        entities:
          - sensor.dark_sky_precip_type
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_dew_point

      - type: entities
        title: Wind Info
        entities:
          - sensor.dark_sky_wind_speed
          - sensor.dark_sky_wind_bearing
          - sensor.dark_sky_nearest_storm_distance

      - type: entities
        title: Pressure Sensors
        entities:
          - sensor.dark_sky_pressure
          - sensor.dark_sky_visibility
          - sensor.dark_sky_ozone

      - type: entities
        title: Atmosphere Updates
        entities:
          - sensor.dark_sky_cloud_coverage



  - title: Social
    id: social
    theme: light-mode
    cards:

  - title: Networking
    id: networking
    theme: light-mode
    cards:

  - title: Netbox Overview
    id: netbox
    theme: light-mode
    panel: true
    cards:
      - type: picture
        title: Netbox Topology
        image: "http://doc.olenoerby.dk/api/extras/topology-maps/1/render/"
#        navigation_path: http://doc.olenoerby.dk

  - title: Information
    id: info
    theme: light-mode
    cards:

  - title: Automations
    id: automation
    theme: light-mode
    cards:
    - type: entities
      title: Automations
      entities:
      - group.all_automations
