# If guests are at home
- alias: Guests at Home
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.guests_at_home
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.guest_automations
    - service: notify.jeeves
      data:
        message: 'Guests have arrived at home.'

# If guests are leaving home
- alias: Guests at Home
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.guests_at_home
      from: 'on'
      to: 'off'
      for:
        minutes: 15
  action:
    - service: homeassistant.turn_on
      entity_id: group.guest_automations   
    - service: notify.jeeves
      data:
        message: 'Guests have left home and the house is in full operation mode again.'
        target: !secret ole_phone_number