# Turn on light in hallway when entering home zone
- alias: Home zone - Turn on light when home
  trigger:
    platform: state
    entity_id: device_tracker.ole_telefon
    to: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: light.entre_loftlampe
    - service: notify.jeeves
      data:
        message: 'You have been detected close to Home, and I have turned on the light in the Hall, Sir.'
        target: !secret ole_phone_number


