# Turn off light in hallway when leaving home zone 15 minutes ago 
- alias: Home zone - Turn on light when evening
  trigger:
    platform: state
    entity_id: device_tracker.ole_telefon
    to: 'not_home'
    for:
      minutes: 15
  action:
    - service: homeassistant.turn_off
      entity_id: light.entre_loftlampe
    - service: notify.jeeves
      data:
        message: 'I have turned off the light in the hallway.'
        target: !secret ole_phone_number