# Home presence - Ole
- alias: 'Ole Presence Detected Away'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: device_tracker.ole_telefon
      from: 'home' 
    - platform: state
      entity_id: device_tracker.argos
      from: 'home' 
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.ole_home

# Hvis Telefon eller Macbook er hjemme eller Mac online er Ole hjemme
- alias: 'Ole Presence Detected Home'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: device_tracker.ole_telefon
      to: 'home' 
    - platform: state
      entity_id: device_tracker.argos
      to: 'home' 
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.ole_home