- alias: 'Jeeves Welcome Home Greeting'
  trigger:
    - platform: zone
      event: enter
      zone: zone.home
      entity_id: device_tracker.ole_telefon
  condition:
    condition: time
    after: '12:00'
  action:
    - service: notify.jeeves
      data_template:
        message: !include response_texts/jeeves_time_of_day.yaml
        target: !secret ole_phone_number
    - service: notify.jeeves
      data:
        message: !include response_texts/jeeves_welcome_home.yaml
        target: !secret ole_phone_number