#Jeeves actions
alias: 'Jeeves Sundown Greeting'
trigger:
  - platform: sun
    event: sunset
action:
  - service: notify.jeeves
    data:
      message: !include response_texts/jeeves_evening_greeting.yaml
      target: !secret ole_phone_number