- alias: 'Good Morning Weekend Message'
  trigger:
    platform: time
    at: '09:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
  action:
    - service: notify.jeeves
      data_template:
        message: !include response_texts/jeeves_morning_greeting.yaml
        target: !secret ole_phone_number