- alias: 'Good Morning Weekday Message'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: notify.jeeves
      data_template:
        message: !include response_texts/jeeves_morning_workday_greeting.yaml
        target: !secret ole_phone_number